const Data = [
    {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    },
    {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    }, {
        img: 'https://cdn.travie.com/news/photo/first/201710/img_19975_1.jpg',
        content: "asdasdasdsadasdsdadsda",
        name: "zxczxczxczcxzc"
    },
]

export default Data